### ISSUE TITLE
minor discrepancy between code and print-out in chapter 7

### ISSUE THREAD

**Issue by almansf** [flythereddflagg/flythereddflagg.github.io#1]
Minor issue, but there's a discrepancy between the code and the print-out of chapter 7 "Escape Characters." Specifically, the code says:

`print("Here is a greek eta character: \u03b7")`

But the print out reads:

Here is a funny character: η

**Comment by flythereddflagg** [comment]
Link to https://flythereddflagg.github.io/python_book/site/07-Escape-Characters/

**Comment by flythereddflagg** [comment]
I have fixed this issue.
