### ISSUE TITLE
spurious/missing sample problem/solution

### ISSUE THREAD

**Issue by jspencer12** [flythereddflagg/flythereddflagg.github.io#2]
https://flythereddflagg.github.io/python_book/site/02-Getting-Started/#troubleshooting-your-installation

This section has "Sample Problem/Sample Solution" perhaps as a placeholder?

**Comment by flythereddflagg** [comment]
I have replaced the space below that section to simply say "this space left intentionally blank" until an issue comes along that I can put there.

**Comment by flythereddflagg** [comment]
Please not that I will not publish these updates and close the issues until I have dealt with a sufficient number of them. Thank you for bringing my attention to this.

**Comment by flythereddflagg** [comment]
I have published the updates.
