### ISSUE TITLE
Python link

### ISSUE THREAD

**Issue by jspencer12** [flythereddflagg/flythereddflagg.github.io#3]
https://flythereddflagg.github.io/python_book/site/02-Getting-Started/#python-3-installation

This section has a link for downloading python that is not actually a link. Is this intentional? Perhaps it needs to be linkified.

**Comment by flythereddflagg** [comment]
I believe I have now addressed this issue. I will include it in the next update.

**Comment by flythereddflagg** [comment]
I have published the updates
