### ISSUE TITLE
recommend adding a glossary

### ISSUE THREAD

**Issue by joehogge** [flythereddflagg/flythereddflagg.github.io#4]
I'm not sure if there's an easy way to do this in github.io, but you might consider adding a glossary for terms that could help readers understand Python-specific (and even programming-specific) terms. Words like "concatenate", etc.

I'd recommend the same, but for acronyms as well.

**Comment by flythereddflagg** [comment]
I have begun adding definitions by hovering over them. If you have specific instances you can add them using the following syntax `<span title="word definition">Word</span>.` I will not do an exhaustive search of words to define but I welcome input on words that should be defined.
